export default {
  app: { title: 'Eussh' },
  titlebar: { settings: 'Settings', debug: 'Debug Log' },
  tabbar: { newTerminal: 'New Terminal', newFileManager: 'File Manager' },
  sidebar: { openServers: 'Open Servers', saved: 'Saved', noServers: 'No servers open', noSaved: 'No saved servers', addServer: 'Add Server', delete: 'Delete' },
  status: { noServer: 'No server selected', connecting: 'Connecting...', error: 'Connection error', disconnected: 'Disconnected', connected: 'connected', latency: '{ms}ms', uploaded: '↑ {name} uploaded', downloaded: '↓ {name} downloaded' },
  terminal: { copy: 'Copy', paste: 'Paste' },
  overview: { title: 'Server Overview', openTerminal: 'Open Terminal', fileManager: 'Files', cpu: 'CPU', memory: 'Memory', storage: 'Disk', timezone: 'Timezone', uptime: 'Uptime', latency: 'Latency', host: 'Host', cores: 'cores' },
  filemanager: { title: 'File Manager', connecting: 'Connecting SFTP...', connectionFailed: 'SFTP connection failed', emptyDir: 'Empty directory', loading: 'Loading...', listView: 'List', iconView: 'Icons', refresh: 'Refresh', newFolder: 'New Folder', newFolderPrompt: 'New folder name:', renamePrompt: 'Rename {name} to:', create: 'Create', cancel: 'Cancel', back: 'Back', forward: 'Forward', open: 'Open', download: 'Download', downloadAsArchive: 'Download as archive', copy: 'Copy', cut: 'Cut', paste: 'Paste', duplicate: 'Duplicate', rename: 'Rename', delete: 'Delete', permissions: 'Permissions', permissionsFor: 'Permissions for {name}', apply: 'Apply', name: 'Name', size: 'Size', modified: 'Modified', owner: 'Owner', group: 'Group', perms: 'Perms', chmodHint: 'e.g. 755, 644, 777', upload: 'Uploading {name}', downloadOp: 'Downloading {name}' },
  connection: { newTitle: 'New Connection', editTitle: 'Edit Connection', name: 'Name', host: 'Host', port: 'Port', username: 'Username', auth: 'Authentication', password: 'Password', privateKey: 'Private Key', keyPath: 'Key Path', passphrase: 'Passphrase (optional)', cancel: 'Cancel', add: 'Add', save: 'Save', nameRequired: 'Name is required', hostRequired: 'Host is required', portInvalid: 'Invalid port', userRequired: 'Username is required', pwRequired: 'Password is required', keyRequired: 'Key path is required' },
  settings: { title: 'Settings', appearance: 'Appearance', theme: 'Theme', light: 'light', dark: 'dark', system: 'system', terminalColors: 'Terminal Colors', accentColor: 'Accent Color', titlebarStyle: 'Title Bar Style', titlebarMacos: 'macOS', titlebarWin11: 'Windows 11', statusbarStyle: 'Status Bar Style', statusbarDefault: 'Default', statusbarAccent: 'Accent', terminal: 'Terminal', fontFamily: 'Font Family', fontSize: 'Font Size', cursor: 'Cursor', block: 'block', bar: 'bar', underline: 'underline', monitoring: 'Monitoring', sysRefresh: 'System refresh', pingInterval: 'Ping interval', showTraffic: 'Traffic monitor', language: 'Language' },
  welcome: { heading: 'Eussh', subtitle: 'SSH Client', hint: 'Add a server from the sidebar to get started' },
  toast: { renderError: 'Render error: {msg}', connectFailed: 'Failed to connect: {msg}', terminalFailed: 'Failed to open terminal: {msg}' },
}
